name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kimhj4270/app1:${{ steps.commit.outputs.short }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'junkmm/GitopsDummy'
          ref: 'main'
          token:  ${{ secrets.MY_REPO_TOKEN }}

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "junkmm@github.actions"

      #- name: Download generated template
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: template-output

      - name: Commit and push generated template
        run: |
          export COMMIT_MESSAGE="Generated template from ${{ github.repository }}/${{ github.ref}}@${{ github.sha }}"
          sed -i 's@kimhj4270/app1:.*@kimhj4270/app1:${{ steps.commit.outputs.short }}@g' deploy.yaml
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push