name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCR_URL }}
          username: ${{ secrets.NCR_ID }}
          password: ${{ secrets.NCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.NCR_URL }}/app1:${{ steps.commit.outputs.short }}

      - name: Deployment
        env:
          NCLOUD_ACCESS_KEY: ${{ secrets.NCP_ACCESS_KEY }}
          NCLOUD_SECRET_KEY: ${{ secrets.NCP_SECRET }}
          NCLOUD_API_GW: https://ncloud.apigw.ntruss.com
        run: |
          echo $NCLOUD_ACCESS_KEY
          echo $NCLOUD_SECRET_KEY
          echo $NCLOUD_API_GW
          # Download kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mkdir -p ~/.local/bin
          mv ./kubectl ~/.local/bin/kubectl

          # Download and configure NCP IAM Authenticator
          curl -o ncp-iam-authenticator -L https://github.com/NaverCloudPlatform/ncp-iam-authenticator/releases/latest/download/ncp-iam-authenticator_linux_amd64
          chmod +x ./ncp-iam-authenticator
          ./ncp-iam-authenticator create-kubeconfig --region KR --clusterUuid 690e4dac-6bcb-4221-9572-16376e5d68c9
          mkdir -p $HOME/bin
          cp ./ncp-iam-authenticator $HOME/bin/ncp-iam-authenticator

          # Update PATH
          export PATH=$PATH:$HOME/bin
          echo 'export PATH=$PATH:$HOME/bin' >> ~/.bash_profile

          # Update Kubernetes Deployment image
          kubectl set image deployment/go-deployment go=${{ secrets.NCR_URL }}/app1:${{ steps.commit.outputs.short }}


